### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by vitich** [ak545/dns-domain-expiration-checker#1]
```
vitich@server:~/dns-domain-expiration-checker$ ./ddec.py -h
  File "./ddec.py", line 237
    f"\tThe {FLG}whois{FR} found in: {FLW}{str_tmp}"
                                                   ^
SyntaxError: invalid syntax
vitich@server:~/dns-domain-expiration-checker$ 

```

**Comment by ak545** [comment]
Please tell me in what environment is this happening?
The name and version of the operating system, the version of Python ...?

**Comment by vitich** [comment]
Thanks! It works with python3.6
It is sad that freenom domains are not supported. Do you plan to add
freenom api?
It would be great!

чт, 16 квіт. 2020 о 22:11 Andrey Klimov <notifications@github.com> пише:

**Comment by vitich** [comment]
$ python3.5 ./ddec.py -d vitich.kiev.ua --print-to-console
--use-extra-external-whois
  File "./ddec.py", line 237
    f"\tThe {FLG}whois{FR} found in: {FLW}{str_tmp}"
                                                   ^
SyntaxError: invalid syntax

Ubuntu 16.04.6 LTS

**Comment by ak545** [comment]
Minimum requirements: Python version 3.6 or higher.
It is strange why this check in the code did not work. By design, the script should have been interrupted if the Python version is lower than 3.6.

```
    # Check Python Version
    if sys.version_info < (3, 6):
        print("Error. Python version 3.6 and above required")
        sys.exit(-1)

```

In any case, you must use Python version 3.6 or higher.

**Comment by ak545** [comment]
Fixed checking of Python version
https://github.com/ak545/dns-domain-expiration-checker/commit/6014e4214512ea71e6c1c304764626ac60814152

**Comment by ak545** [comment]
Thanks!

**Comment by ak545** [comment]
> It is sad that freenom domains are not supported. Do you plan to add freenom api?

No. Sorry.
