### ISSUE TITLE
Not receiving Telegram notifications

### ISSUE THREAD

**Issue by bertusnerd** [ak545/dns-domain-expiration-checker#12]
Hello,

I've configured the script but I'm not receiving any notification on telegram channel. 
Is there any way to debug it?

Thanks!

**Comment by ak545** [comment]
Hello,

Yes, sure.
Take a look at this piece of code:

```
        if CLI.use_telegram:
            res: Optional[Any] = make_report_for_telegram()
            if res:
                if res.status_code != 200:
                    print(f'{FLR}{res.text}')

```    

If any error occurs when sending a message to Telegram, this error should appear in the console.

This is the error message that the website https://api.telegram.org/ returns or the error message that occurs when an attempt to connect to site https://api.telegram.org/ fails.

Also pay attention to the TELEGRAM__* constants.

```
TELEGRAM_TOKEN: str = '<INSERT YOUR TOKEN>'
TELEGRAM_CHAT_ID: str = '<INSERT YOUR CHANNEL ID>'
TELEGRAM_URL: str = f'https://api.telegram.org/bot{TELEGRAM_TOKEN}/'
```

Check if TELEGRAM_TOKEN is correct.
Check if TELEGRAM_CHAT_ID is correct.
Check if your telegram bot is added to the Telegram group or channel where you are trying to send messages.
Check if the site https://api.telegram.org/ is available.

Also note that the maximum message length in a Telegram chat or group is 4096 characters maximum.

Good luck!
