### ISSUE TITLE
Debian 12 - script doesn't work

### ISSUE THREAD

**Issue by renetsk** [ak545/dns-domain-expiration-checker#13]
Hello, some days ago I upgraded my server to debian 12. Script doesn't work now. Every domains got Error.
Any fix please?

**Comment by ak545** [comment]
> Hello, some days ago I upgraded my server to debian 12. Script doesn't work now. Every domains got Error. Any fix please?

![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/5b7b54e1-00f7-4554-b5d7-1b7d85e580f6)


`sudo apt install python3-whois python3-colorama whois`

![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/410ad85a-15ab-4b28-b555-c93d44a9bcf6)
![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/83f4c157-b28a-4d43-952c-ba5db1305e73)

![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/d44d4a37-9802-4c55-acb7-91ece0feeb76)


![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/979749ea-6295-4294-bba0-802ee7abce5e)

**Comment by renetsk** [comment]
I already did that yesterday. Just found, only .sk domains getting error. Can you check that? ie google.sk, zoznam.sk etc.

**Comment by ak545** [comment]
> I already did that yesterday. Just found, only .sk domains getting error. Can you check that? ie google.sk, zoznam.sk etc.

Please, try the new version 0.2.17

**Comment by ak545** [comment]
![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/409129b7-c410-46ce-b184-8fb5b4cb315e)

**Comment by renetsk** [comment]
works fine, thank you

**Comment by ak545** [comment]
Good luck!
