### ISSUE TITLE
.es domains return error

### ISSUE THREAD

**Issue by Mangonels** [ak545/dns-domain-expiration-checker#14]
querying any .es domain will return an Error

![image](https://github.com/ak545/dns-domain-expiration-checker/assets/24245302/98ddd9aa-c8bf-49e9-b630-9347005ae338)

**Comment by ak545** [comment]
For some reason, the fucking Spanish (or European) bureaucrats decided to hide information about domains in the **.es** zone. A stupid act that we cannot influence in any way.

Try new version **0.2.23** (added .es domains) and use it with option **-ee**, **--use-extra-external-whois**

This won't solve your problem, but at least it will be clear what to do next.

![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/0c361357-7c33-487f-a7b7-186b406ff1c8)


https://www.iana.org/whois?q=google.es

**Comment by Mangonels** [comment]
All that option did was change the Days Left error with "Is it Free?" for all .es domains I scanned.

I actually looked for some .es dns's on https://www.dominios.es/en and found out expiry dates. I guess this data is being 
monopolized behind bot blockers?

**Comment by ak545** [comment]
This is what I see on this site for the google.es domain:

![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/ee4cb016-313e-495e-8f77-1cfa519be758)

![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/b4a34629-2836-4add-98dc-f2a957627b81)

![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/d9a762bc-f7c1-4cbb-8db3-9f669b885475)

Fine. Perhaps this site does not like Tor Browser (I first tried to open the site in it) and therefore was rejected.

Then I logged in through a regular proxy.
Having solved 10..15 captcha images (spending about 5..7 minutes on this), I finally got to the right page with the necessary data.

![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/5c8f6db1-e6c0-499c-aac4-cd36a70b358c)

But... Sorry, this is some kind of paranoia on their part. Perhaps someone likes to solve captchas. But definitely not me.

If some registrar intentionally prevents the collection of normal standard Whois information, then so be it.
Please forgive me, but I will not add to the script the passage of an idiotic captcha and the operation of the script from under a proxy.

Maybe later, when their data sharing policy changes for the better...
