### ISSUE TITLE
support domain globbing `{}` `[]` `+` and `*`

### ISSUE THREAD

**Issue by drzraf** [ak545/dns-domain-expiration-checker#16]
Supporting globbing inside domain name could ease some tasks.
Eg: `youtube.(com|org|net)` or `youtube.{com,org,net}` or `youtube[0-9].com`

Some Python libraries like `exrex` do that pretty well.

**Comment by ak545** [comment]
Good idea. I'll do it later...

**Comment by ak545** [comment]
[New version 0.2.26 (Regex-enabled)](https://github.com/ak545/dns-domain-expiration-checker/commit/6c93cb784b372c0fd2e827e1c40c213d1adc7d2c)

![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/8efdc780-4126-47b1-a31b-6f25bd2d2c31)

```
# ! Regexp Group 3
# @regexp:regular_expression cost:0 sleep:4 skip_checking_whois_text_changes

! Regexp Group
@regexp:youtube\.(com|org|net) cost:0 sleep:4 skip_checking_whois_text_changes
@regexp:youtube[0-9]\.com cost:0 skip_checking_whois_text_changes sleep:4
@regexp:youtube([0-9]|1[0-5])\.com cost:0 skip_checking_whois_text_changes sleep:4

```

Thanks for the idea!

**Comment by drzraf** [comment]
please, do you mind dropping my full name from the README.md

**Comment by ak545** [comment]
Replace with "drzraf"?

**Comment by ak545** [comment]
Replaced with "drzraf"
