### ISSUE TITLE
ru domains Error

### ISSUE THREAD

**Issue by woodholly** [ak545/dns-domain-expiration-checker#17]
ddec reports Error for all .ru domains, problem started 2 weeks ago, no problem with other zones.

**Comment by ak545** [comment]
![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/bdfae806-7a04-49c9-92e9-064de0e10a22)

I don't see any problems.
Perhaps the unavailability of **.ru** domains is due to political reasons. Is access to Russian websites blocked in your country?

**Comment by ak545** [comment]
While I make the necessary changes to the script code, you can quickly solve this problem (though without any guarantees) using a SOCKS proxy.

The simplest solution might look like this:
1. Update the required Python packages:
`pip install -U python-whois requests[socks] --user`
2. Launch Tor Browser (just launch it)
3. Add a line to the script
`os.environ['SOCKS']: str = '127.0.0.1:9150'`
![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/42c68880-95e0-4e0e-a38d-d929ef53e77f)

4. Run the script
![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/d55ca570-96d6-479e-9ac3-09f14feb2778)


These actions will route **embedded** whois traffic through the Tor network. However, some whois servers may block requests from Tor, so keep this in mind.

**Comment by ak545** [comment]
[New version 0.2.25 is available](https://github.com/ak545/dns-domain-expiration-checker/commit/e92d765dde3ff526fbc48ffb5df6c00b7240856c)

```
  -piw URL, --proxy-internal-whois URL
                        Socks-proxy link for internal whois engine only (default is None)
                        for example:
                        user:password@socksproxy.someplace.com:8080
                        127.0.0.1:9150

```

**Comment by woodholly** [comment]
Same problem using socks proxy... can this problem be in new python-whois ?
try pip3 install --upgrade python-whois

**Comment by ak545** [comment]
![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/d396288d-76f1-4228-830c-d7dc5a80e94b)

No. The new python-whois, as you can see in the screenshot, works properly.

If you run the script from under some Linux account, then it’s better to update the packages this way

`pip install -U python-whois requests[socks] --user`

Pay attention to the **--user** option
https://pip.pypa.io/en/stable/user_guide/

Check whether Russian domains are generally available to you

`$ whois mail.ru`
![image](https://github.com/ak545/dns-domain-expiration-checker/assets/12557874/3b597f83-9058-47ff-9181-5daf3dc0cc8c)
