### ISSUE TITLE
Error on some .cn and .ph domains

### ISSUE THREAD

**Issue by frcfeng** [ak545/dns-domain-expiration-checker#6]
20. aolab.cn                            2021-05-28           Valid      ( 268)
21. aolab.com.cn                        2021-05-28           Valid      ( 268)
Error trying to connect to socket: closing socket
22. artsoptilab.cn                      -                    Is it Free?   

Error trying to connect to socket: closing socket
 7. 2020iwear.com.ph                    -                    Is it Free?      
Error trying to connect to socket: closing socket
 12. 2020iwear.ph                        -                    Is it Free?      
com.ph and .ph is error
some .cn is error

**Comment by frcfeng** [comment]
> 1. aolab.cn                            2021-05-28           Valid      ( 268)
> 2. aolab.com.cn                        2021-05-28           Valid      ( 268)
>    Error trying to connect to socket: closing socket
> 3. artsoptilab.cn                      -                    Is it Free?
> 
> Error trying to connect to socket: closing socket
> 7. 2020iwear.com.ph - Is it Free?
> Error trying to connect to socket: closing socket
> 12. 2020iwear.ph - Is it Free?
> com.ph and .ph is error
> some .cn is error

Domain Name                                Expiration Date      Days Left        
------------------------------------------ -------------------- -----------------
    1. artsoptilab.cn                      2020-11-20           Soon       (  80)
Error trying to connect to socket: closing socket
    2. 2020iwear.com.ph                    -                    Is it Free?      
    3. 2020iwear.de                        -                    Is it Free?      
Error trying to connect to socket: closing socket
    4. 2020iwear.ph                        -                    Is it Free?
.cn is Unstable
error .de ?

**Comment by ak545** [comment]
![image](https://user-images.githubusercontent.com/12557874/94038592-52f3fa00-fdcf-11ea-9e86-7a588470e7a1.png)
