### ISSUE TITLE
feature:  don't SMTP_AUTH  by default

### ISSUE THREAD

**Issue by akhepcat** [ak545/dns-domain-expiration-checker#7]
This small patch changes the default from *always auth*  to  *auth-when-selected* via a new CLI flag.

[ddec.diff.txt](https://github.com/ak545/dns-domain-expiration-checker/files/5617823/ddec.diff.txt)

Without this, the default is to always authorize the SMTP connection, which isn't always needed.

**Comment by ak545** [comment]
Your comments are logical. 
They have been taken into account since version 0.2.8.
Thanks a lot!
