### ISSUE TITLE
error when checking  '.gov'  domains

### ISSUE THREAD

**Issue by akhepcat** [ak545/dns-domain-expiration-checker#8]
It appears that the parser doesn't correctly follow the US'   DOTGOV   whois server output:

    $ whois whitehouse.gov
    % DOTGOV WHOIS Server ready
       Domain Name: WHITEHOUSE.GOV
       Status: ACTIVE
    
    >>> Last update of whois database: 2020-12-06T21:01:19Z <<<
    
    --
    
    $ ddec.py -c -nb -d whitehouse.gov
    
    ------------------------------------------ -------------------- -----------------
    Domain Name                                Expiration Date      Days Left        
    ------------------------------------------ -------------------- -----------------
        1. whitehouse.gov                      -                    Error            
    ------------------------------------------ -------------------- -----------------
    Process complete.
    
(this error is the same for all .gov domains that i've tested)

**Comment by ak545** [comment]
Sure!

.gov (from the English government) is a general top-level domain (zone) for US government organizations. The sponsoring organization is the General Services Administration.
Domains in this zone have only one feature - a status feature (active or inactive). It will not work to intercept domains from this zone, for example, by tracking the expiration date of the domain registration. Any changes in this zone are made only at the initiative of the US government. Therefore, it makes no sense to monitor domains in this zone for registration expiration dates.

The main purpose of my script is to monitor **the number of days** left before the expiration of the domain registration period. .Gov domains do not provide this information. For this reason, if you try to monitor a domain from the .gov zone with my script, then the result of such an attempt will be an error.

**Comment by akhepcat** [comment]
Makes sense -   I wasn't sure if it was a better idea to silently ignore within the script (returning a "no monitoring available" )   or just filter on my  pre-parser  from the dns zones file.

I'll pre-filter for now;  we've only got  one  .gov   that we're handling DNS for.

thanks.

**Comment by ak545** [comment]
The problem is that there are a lot of such situations and it is impossible to foresee all of them because domain registrars sometimes do not adhere to any specific standard, but indicate information in free text form, as they please. Alternatively, you can display the original text of such "creativity". But this will break potential processing of the results of my script by third-party scripts, for example, when working in pipelines. I don’t know how much it would be justified to complicate the life of potential users of my script.

**Comment by ak545** [comment]
Added new options and handling of unsupported domains.

**Comment by akhepcat** [comment]
Ah, nice way to solve that issue at a generic level.   Thanks for keeping an open mind toward it!
