### ISSUE TITLE
Feature:  allow amended custom subject text

### ISSUE THREAD

**Issue by akhepcat** [ak545/dns-domain-expiration-checker#9]
Attached patch allows for adding additional text to the email subject, for incorporating run information (time started, domain-list information, etc)  while still keeping the original subject "prefixed"  for sorting

[ddec.diff.txt](https://github.com/ak545/dns-domain-expiration-checker/files/5649544/ddec.diff.txt)

(Same style as previous patch)

    $ ./ddec.py -h | grep -i email.subject
       -subject STRING, --email-subject STRING
                            Append custom text to the email subject (default is None)

**Comment by ak545** [comment]
I agree. I will add this option shortly. Thanks for the idea!

**Comment by ak545** [comment]
Added
